### ISSUE TITLE
Issue with hiragana's second gen blog

### ISSUE THREAD

**Issue by wasd0109** [MilitaryRiotLab/Keyakizaka46-Blog-archiver#1]
the kaomoji  ( ᐛ )٩و that some hiragana second gen use seems to trigger unknown bug that lead to deformed blog spacing etc

**Comment by MilitaryRiotLab** [comment]
Can you provide the link to the blog post?

**Comment by wasd0109** [comment]
http://www.keyakizaka46.com/s/k46o/diary/detail/13814?ima=0000&cd=member

https://k46.akb48.work/2018/Feb/08/%E3%81%91%E3%82%84%E3%81%8D%E5%9D%8246%202%E6%9C%9F%E7%94%9F/%E4%BB%8A%E5%87%BA%E3%81%9B%E3%82%8B%E6%9C%80%E5%A4%A7%E9%99%90%20%20%E3%81%91%E3%82%84%E3%81%8D%E5%9D%8246%202%E6%9C%9F%E7%94%9F%E3%81%AE%E6%9D%BE%E7%94%B0%E5%A5%BD%E8%8A%B1%E3%81%A7%E3%81%99(%5E%5E)/

**Comment by MilitaryRiotLab** [comment]
Fixed for now.
### This is before the fix,
> ![screen shot 2018-02-11 at 00 33 00](https://user-images.githubusercontent.com/11252231/36064268-5dda2c1c-0ec3-11e8-983c-fcf607985b43.png)
----------
### This is from the official website,

> ![screen shot 2018-02-11 at 00 10 59](https://user-images.githubusercontent.com/11252231/36064104-eaf41b6a-0ec0-11e8-9c11-c4e3f5f92582.png)
----------
### This is the after the fix,
> ![screenshot-2018-2-11 https k46 akb48 work](https://user-images.githubusercontent.com/11252231/36064103-e85a60da-0ec0-11e8-96a5-6200eb745cdc.png)
----------

The underlined words, `2月10日発売 MAQUEEさん vol.125`, are separated incorrectly after the fix, ****it cannot be fixed****.

Thank you for reporting, please let me know if there is another bug. 😄
